from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

import eda_llm_assistant.methodology as meth
from eda_llm_assistant.config import EDASectionConfig
from eda_llm_assistant.utils import ensure_dir


def _describe_stats_rows(desc: dict[str, Any], cols: list[str]) -> list[dict[str, Any]]:
    """Normalize `DataFrame.describe().to_dict()` (column-oriented) or row-oriented dict."""
    if not desc or not cols:
        return []
    first = cols[0]
    if first in desc and isinstance(desc[first], dict):
        rows = []
        for c in cols:
            d = desc.get(c)
            if not isinstance(d, dict):
                continue
            rows.append(
                {
                    "column": c,
                    "mean": d.get("mean"),
                    "std": d.get("std"),
                    "min": d.get("min"),
                    "p50": d.get("50%"),
                    "max": d.get("max"),
                }
            )
        return rows
    rows = []
    for c in cols:
        try:
            rows.append(
                {
                    "column": c,
                    "mean": desc.get("mean", {}).get(c),
                    "std": desc.get("std", {}).get(c),
                    "min": desc.get("min", {}).get(c),
                    "p50": desc.get("50%", {}).get(c),
                    "max": desc.get("max", {}).get(c),
                }
            )
        except Exception:
            continue
    return rows


def render_markdown(
    *,
    title: str,
    data_dictionary_df: pd.DataFrame,
    overview: dict[str, Any],
    col_types: dict[str, Any],
    target: str | None,
    user_dictionary_count: int,
    duplicates: dict[str, Any] | None,
    missing_df: pd.DataFrame | None,
    quality_df: pd.DataFrame,
    outliers_df: pd.DataFrame | None,
    numeric: dict[str, Any] | None,
    categorical: dict[str, Any] | None,
    corr_high_pairs: list[dict[str, Any]] | None,
    corr_with_target_df: pd.DataFrame | None,
    applied_transformations: list[str],
    suggested_transformations: list[str],
    artifacts: dict[str, str],
    llm_text: str | None,
    provenance: dict[str, str],
    sections: EDASectionConfig,
    plot_sample_note: str | None,
    data_source_path: str,
    excluded_from_analysis: list[str],
    column_intelligence_df: pd.DataFrame | None,
    supervised_bundle: dict[str, Any] | None,
) -> str:
    lines: list[str] = []

    lines.append(f"# {title}")
    lines.append("")
    lines.append("This report is generated by **EDA LLM Assistant**: exploratory analysis for tabular data, ")
    lines.append("with explicit notes on **which methods** are used and **how** they are applied.")
    lines.append("")

    lines.append("## Report output (how to read this document)")
    lines.append("")
    lines.append(
        f"- **Input data source** (from config): `{data_source_path}`\n"
        "- **Sections** follow: dictionary → **column intelligence** → structure → validation → "
        "transformations → visualizations → **supervised (if target set)** → other notes → provenance.\n"
        "- **Plots** are embedded as relative paths under the output folder.\n"
        "- Method notes appear as blockquotes (lines starting with `>`) under each subsection."
    )
    if plot_sample_note:
        lines.append(f"- **Plot sampling:** {plot_sample_note}")
    lines.append("")

    # --- 1. Data dictionary ---
    lines.append("## 1. Data dictionary")
    lines.append("")
    lines.append(f"> {meth.paragraph_dictionary_inference(user_dictionary_count)}")
    lines.append("")
    if not data_dictionary_df.empty:
        lines.append(data_dictionary_df.to_markdown(index=False))
    else:
        lines.append("_No columns._")
    lines.append("")
    lines.append(
        "*If inferred meanings are wrong, replace them in config under `dictionary:` "
        "or in your organization’s official data dictionary.*"
    )
    lines.append("")

    # --- 2. Column intelligence ---
    lines.append("## 2. Column intelligence")
    lines.append("")
    lines.append(f"> {meth.paragraph_column_intelligence()}")
    lines.append("")
    if sections.column_intelligence and column_intelligence_df is not None and not column_intelligence_df.empty:
        lines.append(column_intelligence_df.to_markdown(index=False))
        lines.append("")
        _embed_artifact(lines, artifacts, "column_intelligence.csv", "Column intelligence CSV")
    elif not sections.column_intelligence:
        lines.append("_Section disabled in config (`sections.column_intelligence`)._")
    else:
        lines.append("_No column intelligence table produced._")
    lines.append("")

    # --- 3. Data structure ---
    lines.append("## 3. Data structure")
    lines.append("")
    lines.append(f"> {meth.paragraph_identifier_exclusion()}")
    lines.append("")
    if excluded_from_analysis:
        lines.append(
            "**Excluded from statistical analysis (identifiers / manual):** "
            + ", ".join(f"`{c}`" for c in excluded_from_analysis)
        )
        lines.append("")
    lines.append("### 3.1 Data summary")
    lines.append("")
    shape = overview.get("shape", {})
    lines.append(f"- **Rows (n):** {shape.get('rows')}")
    lines.append(f"- **Columns (p):** {shape.get('cols')}")
    lines.append(f"- **Approx. memory:** {overview.get('memory_mb')} MB (pandas `memory_usage(deep=True)`)")
    lines.append("")
    _embed_artifact(lines, artifacts, "sample_rows.csv", "Sample rows (CSV)")

    lines.append("### 3.2 Numeric vs categorical (and other roles)")
    lines.append("")
    lines.append(f"> {meth.paragraph_type_inference()}")
    lines.append("")
    lines.append("| Role | Columns (count) | Names |")
    lines.append("|---:|---:|---|")
    lines.append(f"| Numeric | {len(col_types.get('numeric', []))} | {', '.join(col_types.get('numeric', [])) or '—'} |")
    lines.append(
        f"| Categorical (object/category) | {len(col_types.get('categorical', []))} | "
        f"{', '.join(col_types.get('categorical', [])) or '—'} |"
    )
    lines.append(f"| Boolean | {len(col_types.get('boolean', []))} | {', '.join(col_types.get('boolean', [])) or '—'} |")
    lines.append(f"| Datetime | {len(col_types.get('datetime', []))} | {', '.join(col_types.get('datetime', [])) or '—'} |")
    lines.append("")

    lines.append("### 3.3 Dependent vs independent variables")
    lines.append("")
    lines.append(f"> {meth.paragraph_dependent_independent(target)}")
    lines.append("")

    # --- 4. Data validation ---
    lines.append("## 4. Data validation")
    lines.append("")

    lines.append("### 4.1 Missing values")
    lines.append("")
    lines.append(f"> {meth.paragraph_missing_values()}")
    lines.append("")
    if sections.missing_values and missing_df is not None:
        top_missing = missing_df[missing_df["missing_count"] > 0].head(40)
        if top_missing.empty:
            lines.append("No missing values detected.")
        else:
            lines.append(top_missing.to_markdown(index=False))
        lines.append("")
        _embed_artifact(lines, artifacts, "missing_values_bar.png", "Missing values bar chart")
        _embed_artifact(lines, artifacts, "missing_values_heatmap.png", "Missing values heatmap")
    elif not sections.missing_values:
        lines.append("_Section disabled in config._")
    lines.append("")

    lines.append("### 4.2 Duplicate records")
    lines.append("")
    lines.append(f"> {meth.paragraph_duplicates()}")
    lines.append("")
    if sections.duplicates and duplicates:
        lines.append(f"- **Duplicate rows:** {duplicates.get('duplicate_rows')}")
        lines.append(f"- **Duplicate %:** {duplicates.get('duplicate_pct'):.4f}%")
    elif not sections.duplicates:
        lines.append("_Section disabled in config._")
    lines.append("")

    lines.append("### 4.3 Anomalies / consistency (heuristic checks)")
    lines.append("")
    lines.append(f"> {meth.paragraph_quality_heuristics()}")
    lines.append("")
    if not quality_df.empty:
        lines.append(quality_df.to_markdown(index=False))
    else:
        lines.append("No heuristic flags from the built-in checks (see methodology for limits).")
    lines.append("")

    lines.append("### 4.4 Outliers (IQR fences)")
    lines.append("")
    lines.append(f"> {meth.paragraph_iqr_outliers()}")
    lines.append("")
    if sections.outliers_iqr and outliers_df is not None:
        if outliers_df.empty:
            lines.append("No numeric columns for IQR outlier counts.")
        else:
            lines.append(outliers_df.head(60).to_markdown(index=False))
    elif not sections.outliers_iqr:
        lines.append("_Section disabled in config._")
    lines.append("")

    # --- 5. Data transformation ---
    lines.append("## 5. Data transformation")
    lines.append("")
    lines.append(f"> {meth.paragraph_transformation_notes()}")
    lines.append("")
    lines.append("### 5.1 Applied in this run")
    lines.append("")
    for item in applied_transformations:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("### 5.2 Suggested next steps (not applied automatically)")
    lines.append("")
    if suggested_transformations:
        for item in suggested_transformations:
            lines.append(f"- {item}")
    else:
        lines.append("No generic transformation suggestions from heuristics, or dataset is small/simple.")
    lines.append("")

    # --- 6. Visualization ---
    lines.append("## 6. Data visualization")
    lines.append("")
    lines.append("### 6.1 Numeric distributions")
    lines.append("")
    lines.append(f"> {meth.paragraph_describe()}")
    lines.append("")
    lines.append(f"> {meth.paragraph_plots_numeric()}")
    lines.append("")
    if sections.numeric_summary:
        if numeric and numeric.get("describe"):
            desc = numeric["describe"]
            cols = list((numeric.get("columns") or []))[:40]
            rows = _describe_stats_rows(desc, cols)
            if rows:
                lines.append(pd.DataFrame(rows).to_markdown(index=False))
        lines.append("")
        _embed_artifact(lines, artifacts, "numeric_distributions.png", "Numeric distributions")
        _embed_artifact(lines, artifacts, "numeric_boxplots.png", "Numeric boxplots")
    else:
        lines.append("_Section disabled in config._")
    lines.append("")

    lines.append("### 6.2 Categorical distributions")
    lines.append("")
    lines.append(f"> {meth.paragraph_categorical_top()}")
    lines.append("")
    lines.append(f"> {meth.paragraph_plots_categorical()}")
    lines.append("")
    if sections.categorical_summary and categorical:
        top_values = categorical.get("top_values") or {}
        if not top_values:
            lines.append("No categorical columns.")
        else:
            for c, values in list(top_values.items())[:25]:
                lines.append(f"#### `{c}`")
                lines.append("")
                lines.append(pd.DataFrame(values).to_markdown(index=False))
                lines.append("")
        _embed_artifact(lines, artifacts, "categorical_top_values.png", "Categorical top values")
    elif not sections.categorical_summary:
        lines.append("_Section disabled in config._")
    lines.append("")

    lines.append("### 6.3 Correlations")
    lines.append("")
    lines.append(f"> {meth.paragraph_pearson_correlation()}")
    lines.append("")
    lines.append(f"> {meth.paragraph_plots_correlation()}")
    lines.append("")
    if corr_with_target_df is not None and not corr_with_target_df.empty:
        lines.append(f"#### Association with target `{target}` (Pearson)")
        lines.append("")
        lines.append(corr_with_target_df.head(25).to_markdown(index=False))
        lines.append("")
    if sections.correlations and corr_high_pairs is not None:
        if len(corr_high_pairs) == 0:
            lines.append(
                f"No pairs with |r| ≥ threshold (edit `report.corr_threshold`; current logic uses absolute Pearson r)."
            )
        else:
            lines.append(pd.DataFrame(corr_high_pairs[:50]).to_markdown(index=False))
        lines.append("")
        _embed_artifact(lines, artifacts, "correlation_heatmap.png", "Correlation heatmap")
    elif not sections.correlations:
        lines.append("_Section disabled in config._")
    lines.append("")

    ts_plots = [k for k in artifacts if k.startswith("time_series_count_") and k.endswith(".png")]
    if ts_plots:
        lines.append("### 6.4 Time-based row counts (if datetime columns exist)")
        lines.append("")
        lines.append(f"> {meth.paragraph_plots_time_series()}")
        lines.append("")
        for key in sorted(ts_plots):
            _embed_artifact(lines, artifacts, key, key.replace(".png", "").replace("_", " "))

    # --- 7. Supervised / target-driven EDA ---
    lines.append("## 7. Supervised / target-driven EDA")
    lines.append("")
    lines.append(f"> {meth.paragraph_supervised_eda()}")
    lines.append("")

    def _fmt_num(v: Any, nd: int = 4) -> str:
        try:
            x = float(v)
            if x != x or x in (float("inf"), float("-inf")):
                return "n/a"
            return f"{x:.{nd}f}"
        except (TypeError, ValueError):
            return "n/a"

    if not sections.supervised_eda:
        lines.append("_Section disabled in config (`sections.supervised_eda`)._")
    elif not target:
        lines.append("Set `columns.target` in config to enable supervised tables and tests.")
    elif not supervised_bundle:
        lines.append(
            "_Could not build supervised summary (is `target` present in the analysis dataframe after exclusions?)._"
        )
    else:
        kind = supervised_bundle.get("kind")
        tgt = supervised_bundle.get("target")
        lines.append(f"**Target column:** `{tgt}`  \n**Type (for this section):** `{kind}`")
        lines.append("")
        prof = supervised_bundle.get("target_profile")
        if prof is not None and isinstance(prof, pd.DataFrame) and not prof.empty:
            lines.append("### 7.1 Target profile")
            lines.append("")
            lines.append(prof.to_markdown(index=False))
            lines.append("")
            _embed_artifact(lines, artifacts, "supervised_target_distribution.png", "Target distribution")

        if kind == "categorical":
            for block in supervised_bundle.get("numeric_by_categorical_target") or []:
                feat = block.get("feature")
                tab = block.get("table")
                if tab is not None and not tab.empty:
                    lines.append(f"#### Numeric feature `{feat}` by target level")
                    lines.append("")
                    lines.append(tab.to_markdown(index=False))
                    lines.append("")
            lines.append("#### Chi-square tests (target vs categorical features)")
            lines.append("")
            chi = supervised_bundle.get("chi_square_tests") or []
            if not chi:
                lines.append("_No tests run (too many categories or insufficient table shape)._")
            for row in chi:
                feat = row.get("feature", "?")
                lines.append(f"**`{feat}`**")
                lines.append("")
                if "error" in row:
                    lines.append(f"_Could not compute: {row['error']}_")
                else:
                    lines.append(
                        f"- chi-squared = {_fmt_num(row.get('chi2'))}, p = {_fmt_num(row.get('pvalue'))}, "
                        f"dof = {row.get('dof')}, table shape {row.get('table_shape')}, "
                        f"{row.get('pct_small_expected_lt5')}% of cells have expected count < 5."
                    )
                    lines.append("")
                    lines.append(f"> {row.get('note', '')}")
                lines.append("")
        elif kind == "numeric":
            for block in supervised_bundle.get("categorical_group_stats_numeric_target") or []:
                feat = block.get("feature")
                tab = block.get("table")
                if tab is not None and not tab.empty:
                    lines.append(f"#### Numeric target by `{feat}`")
                    lines.append("")
                    lines.append(tab.to_markdown(index=False))
                    lines.append("")
            lines.append("#### Kruskal–Wallis tests (target across categorical groups)")
            lines.append("")
            kw = supervised_bundle.get("kruskal_wallis_tests") or []
            if not kw:
                lines.append("_No tests run (too few groups or insufficient data)._")
            for row in kw:
                feat = row.get("feature", "?")
                lines.append(f"**`{feat}`**")
                lines.append("")
                if "error" in row:
                    lines.append(f"_Could not compute: {row['error']}_")
                else:
                    lines.append(
                        f"- H = {_fmt_num(row.get('statistic'))}, p = {_fmt_num(row.get('pvalue'))}, "
                        f"groups = {row.get('n_groups')}"
                    )
                    lines.append("")
                    lines.append(f"> {row.get('note', '')}")
                lines.append("")
        else:
            lines.append("_Target dtype is not split into numeric vs categorical tests; profile shown above only._")

        if kind in ("numeric", "categorical"):
            _embed_artifact(lines, artifacts, "supervised_bivariate_boxplots.png", "Supervised bivariate boxplots")
    lines.append("")

    # --- 8. Other ---
    lines.append("## 8. Other considerations")
    lines.append("")
    lines.append(f"> {meth.paragraph_other_considerations()}")
    lines.append("")
    html_links = {k: v for k, v in artifacts.items() if k.endswith(".html")}
    if html_links:
        lines.append("Optional packaged HTML reports:")
        for name, rel in html_links.items():
            lines.append(f"- [{name}]({rel})")
        lines.append("")

    if llm_text:
        lines.append("### LLM-generated narrative (optional)")
        lines.append("")
        lines.append("> Generated from a compact JSON summary of EDA tables, not from raw row-level data.")
        lines.append("")
        lines.append(llm_text.strip())
        lines.append("")

    # --- 9. Provenance ---
    lines.append("## 9. Output provenance")
    lines.append("")
    lines.append("| Key | Value |")
    lines.append("|---|---|")
    for k, v in provenance.items():
        lines.append(f"| {k} | {v} |")
    lines.append("")

    return "\n".join(lines).strip() + "\n"


def write_markdown(md: str, out_dir: Path, filename: str = "report.md") -> Path:
    ensure_dir(out_dir)
    p = out_dir / filename
    p.write_text(md, encoding="utf-8")
    return p


def markdown_to_html(md: str, title: str) -> str:
    try:
        import markdown as mdlib
    except Exception:
        safe = md.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"<html><head><meta charset='utf-8'><title>{title}</title></head><body><pre>{safe}</pre></body></html>"

    body = mdlib.markdown(md, extensions=["tables", "fenced_code"])
    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.55; margin: 24px; max-width: 1100px; }}
    table {{ border-collapse: collapse; width: 100%; overflow-x: auto; display: block; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
    th {{ background: #f6f8fa; }}
    blockquote {{ margin: 12px 0; padding: 10px 16px; background: #f6f8fa; border-left: 4px solid #0366d6;
                  color: #24292e; font-size: 0.95rem; }}
    code {{ background: #f6f8fa; padding: 0 4px; border-radius: 4px; }}
    pre code {{ display: block; padding: 12px; overflow-x: auto; }}
    img {{ max-width: 100%; height: auto; border: 1px solid #eee; border-radius: 8px; }}
    h1, h2, h3, h4 {{ margin-top: 28px; }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""


def write_html(html: str, out_dir: Path, filename: str = "report.html") -> Path:
    ensure_dir(out_dir)
    p = out_dir / filename
    p.write_text(html, encoding="utf-8")
    return p


def _embed_artifact(lines: list[str], artifacts: dict[str, str], key: str, alt: str) -> None:
    path = artifacts.get(key)
    if not path:
        return
    if key.endswith(".csv"):
        lines.append(f"- Sample export: [`{key}`]({path})")
    else:
        lines.append(f"![{alt}]({path})")
    lines.append("")
